apiVersion: v1
kind: Service
metadata:
  name: pravega-webhook-svc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    component: pravega-operator
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pravega-webhook-config
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.webhookCert.generate }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ template "pravega-operator.fullname" . }}-cert
    {{- else }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.webhookCert.certName }}
    {{- end }}
webhooks:
- clientConfig:
    service:
      name: pravega-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /validate-pravega-pravega-io-v1beta1-pravegacluster
  name: pravegawebhook.pravega.io
  failurePolicy: Fail
  rules:
  - apiGroups:
    - pravega.pravega.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pravegaclusters
    scope: "*"
  admissionReviewVersions: ["v1beta1", "v1"]
  sideEffects: None
  timeoutSeconds: 30
