replicas: 6

resources:
  requests:
    cpu: 2000m
    memory: 8Gi
  limits:
    cpu: 4000m
    memory: 16Gi

storage:
  ledger:
    className:
    volumeSize: 250Gi
  journal:
    className:
    volumeSize: 250Gi
  index:
    className:
    volumeSize: 10Gi

jvmOptions:
  memoryOpts: ["-Xms2g", "-XX:MaxDirectMemorySize=8g", "-XX:+ExitOnOutOfMemoryError", "-XX:+CrashOnOutOfMemoryError", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/tmp/dumpfile/heap", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=50.0"]
