{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "bookkeeper-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bookkeeper-operator.commonLabels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
{{- end }}
