apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookkeeper-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bookkeeper-operator.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "bookkeeper-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "bookkeeper-operator.fullname" . }}
        component: bookkeeper-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "bookkeeper-operator.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - bookkeeper-operator
        {{- if .Values.testmode.enabled }}
        args: [-test]
        {{- end }}
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.watchNamespace }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "bookkeeper-operator.fullname" . }}
        volumeMounts:
        - name: webhook-cert
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
          readOnly: true
        - name: versions-volume
          mountPath: "/tmp/config"
      volumes:
      - name: webhook-cert
        secret:
          {{- if .Values.webhookCert.generate }}
          secretName: {{ template "bookkeeper-operator.fullname" . }}-cert-tls-bk
          {{- else }}
          secretName: {{ .Values.webhookCert.secretName }}
          {{- end }}
      - name: versions-volume
        configMap:
          name: bk-supported-versions-map
